[postgres]
driver = "postgres"
source = "postgresql://root:root@192.168.172.132:5432/imchat?sslmode=disable"
migrate_url = "file://db/pg/migration"

[server]
grpc_server_address = "0.0.0.0:9090"
http_server_address = "0.0.0.0:9091"

[token]
token_symmetric_key = "plokmnjiuhbvgytfcxdreszawq564738"
access_token_duration = "30m"
