[postgres]
driver = "postgres"
source = "postgresql://root:root@localhost:5432/imchat?sslmode=disable?TimeZone=Asiz/Shanghai"
migrate_url = "file://db/pg/migration"

[server]
grpc_server_address = "0.0.0.0:9090"
http_server_address = "0.0.0.0:9091"

[token]
token_symmetric_key = "plokmnjiuhbvgytfcxdreszawq564738"
access_token_duration = "30m"