[postgres]
driver = "postgres"
source = "postgresql://postgres:postgres@localhost:5432/imchat?sslmode=disable&timeZone=Asia/Shanghai"
migrate_url = "file://db/migration"

[server]
grpc_server_address = "0.0.0.0:9090"
http_server_address = "0.0.0.0:9091"

[token]
token_symmetric_key = "plokmnjiuhbvgytfcxdreszawq564738"
access_token_duration = "30m"

[redis]
address = "localhost:6379"
password = ""
db = 0

[logger]
path = "logs/chat.log"
level = "debug"