// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: contact.sql

package db

import (
	"context"
)

const addContact = `-- name: AddContact :one
INSERT INTO contact (
    owner_id, target_id, type
) VALUES (
    $1, $2, $3
)
RETURNING id, owner_id, target_id, type, created_at
`

type AddContactParams struct {
	OwnerID  int64 `json:"owner_id"`
	TargetID int64 `json:"target_id"`
	Type     int16 `json:"type"`
}

func (q *Queries) AddContact(ctx context.Context, arg AddContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, addContact, arg.OwnerID, arg.TargetID, arg.Type)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TargetID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
