// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: examine.sql

package db

import (
	"context"
)

const addExamine = `-- name: AddExamine :one
INSERT INTO examine (
    owner_id, target_id, type
) VALUES (
    $1, $2, $3
)
RETURNING owner_id, target_id, type, created_at
`

type AddExamineParams struct {
	OwnerID  int64 `json:"owner_id"`
	TargetID int64 `json:"target_id"`
	Type     int16 `json:"type"`
}

func (q *Queries) AddExamine(ctx context.Context, arg AddExamineParams) (Examine, error) {
	row := q.db.QueryRowContext(ctx, addExamine, arg.OwnerID, arg.TargetID, arg.Type)
	var i Examine
	err := row.Scan(
		&i.OwnerID,
		&i.TargetID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExamine = `-- name: DeleteExamine :exec
DELETE FROM examine 
WHERE owner_id = $1 AND target_id = $2 AND type = $3
`

type DeleteExamineParams struct {
	OwnerID  int64 `json:"owner_id"`
	TargetID int64 `json:"target_id"`
	Type     int16 `json:"type"`
}

func (q *Queries) DeleteExamine(ctx context.Context, arg DeleteExamineParams) error {
	_, err := q.db.ExecContext(ctx, deleteExamine, arg.OwnerID, arg.TargetID, arg.Type)
	return err
}

const getExamine = `-- name: GetExamine :many
SELECT owner_id, target_id, type, created_at FROM examine
WHERE owner_id = $1
`

func (q *Queries) GetExamine(ctx context.Context, ownerID int64) ([]Examine, error) {
	rows, err := q.db.QueryContext(ctx, getExamine, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Examine{}
	for rows.Next() {
		var i Examine
		if err := rows.Scan(
			&i.OwnerID,
			&i.TargetID,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
