// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: group_member_ship.sql

package db

import (
	"context"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_member_ships(
    user_id, group_id, nickname, role
)
VALUES(
    $1, $2, $3, $4
)
RETURNING id, user_id, group_id, nickname, role, mute, created_at, updated_at
`

type AddGroupMemberParams struct {
	UserID   int32  `json:"user_id"`
	GroupID  int32  `json:"group_id"`
	Nickname string `json:"nickname"`
	Role     int16  `json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg *AddGroupMemberParams) (GroupMemberShip, error) {
	row := q.db.QueryRow(ctx, addGroupMember,
		arg.UserID,
		arg.GroupID,
		arg.Nickname,
		arg.Role,
	)
	var i GroupMemberShip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Nickname,
		&i.Role,
		&i.Mute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
