// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: group.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    creator_id, group_name, icon, description
) VALUES(
    $1, $2, $3, $4
)
RETURNING id, creator_id, group_name, icon, description, notice, created_at, updated_at
`

type CreateGroupParams struct {
	CreatorID   int32  `json:"creator_id"`
	GroupName   string `json:"group_name"`
	Icon        string `json:"icon"`
	Description string `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg *CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.CreatorID,
		arg.GroupName,
		arg.Icon,
		arg.Description,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.GroupName,
		&i.Icon,
		&i.Description,
		&i.Notice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
