// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: message.sql

package db

import (
	"context"
)

const addMessage = `-- name: AddMessage :one
INSERT INTO messages (
    send_id, receive_id, content
) VALUES (
    $1, $2, $3
)
RETURNING id, send_id, receive_id, content, send_time, receive_time
`

type AddMessageParams struct {
	SendID    int32  `json:"send_id"`
	ReceiveID int32  `json:"receive_id"`
	Content   string `json:"content"`
}

func (q *Queries) AddMessage(ctx context.Context, arg *AddMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, addMessage, arg.SendID, arg.ReceiveID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SendID,
		&i.ReceiveID,
		&i.Content,
		&i.SendTime,
		&i.ReceiveTime,
	)
	return i, err
}
