// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Friend struct {
	// 用户Id
	UserID int32 `json:"user_id"`
	// 好友Id
	FriendID int32 `json:"friend_id"`
	// 好友备注
	Note string `json:"note"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type FriendApply struct {
	// 所有者Id
	ApplyID int32 `json:"apply_id"`
	// 目标对象Id
	ReplyID int32 `json:"reply_id"`
	// 申请描述
	ApplyDesc string `json:"apply_desc"`
	// 备注
	Note string `json:"note"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	// 用户Id
	ID int32 `json:"id"`
	// 用户名
	Username string `json:"username"`
	// 用户昵称
	Nickname string `json:"nickname"`
	// 密码
	Password string `json:"password"`
	// 邮箱
	Email string `json:"email"`
	// 性别, 0 未知, 1 男, 2 女
	Gender int16 `json:"gender"`
	// 用户头像
	Avatar string `json:"avatar"`
	// 密码更新时间
	PasswordChangedAt time.Time `json:"password_changed_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

type UserLoginLog struct {
	// 日志Id
	ID int64 `json:"id"`
	// 用户id
	UserID int32 `json:"user_id"`
	// 登录时间
	LoginTime time.Time `json:"login_time"`
	// 登录ip
	LoginIp string `json:"login_ip"`
	// 登录ip所在地
	LoginIpRegion string `json:"login_ip_region"`
	// 是否登录异常, t: 异常, f: 非异常
	IsLoginExceptional bool `json:"is_login_exceptional"`
	// 登录平台
	Platform string `json:"platform"`
	// user_agent
	UserAgent string `json:"user_agent"`
}
