// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type FriendGroupApply struct {
	// 主键Id
	ID int64 `json:"id"`
	// 申请者用户Id
	UserID int32 `json:"user_id"`
	// 响应者Id(好友/群组Id)
	TargetID int32 `json:"target_id"`
	// 申请描述
	Description string `json:"description"`
	// 申请类型, 1: 好友, 2: 群组
	ApplyType int16 `json:"apply_type"`
	// 申请状态, 1: 待确认, 2: 已确认, 3: 已拒绝
	Status int16 `json:"status"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 响应时间
	UpdatedAt time.Time `json:"updated_at"`
}

type Friendship struct {
	// 主键Id
	ID int64 `json:"id"`
	// 用户Id
	UserID int32 `json:"user_id"`
	// 好友Id
	FriendID int32 `json:"friend_id"`
	// 好友备注
	Comment string `json:"comment"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

type Group struct {
	// 主键Id
	ID int64 `json:"id"`
	// 创建者Id
	CreatorID int32 `json:"creator_id"`
	// 群组名
	GroupName string `json:"group_name"`
	// 群员人数
	GroupMemberQuantity int32 `json:"group_member_quantity"`
	// 群组描述
	Description string `json:"description"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

type GroupMemberShip struct {
	// 主键Id
	ID int64 `json:"id"`
	// 用户Id
	UserID int32 `json:"user_id"`
	// 群组Id
	GroupID int32 `json:"group_id"`
	// 群员角色, 1: 群主, 2: 管理员, 3: 普通成员
	Role int16 `json:"role"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

type Message struct {
	// 主键Id
	ID int64 `json:"id"`
	// 消息发送者Id
	SenderID int32 `json:"sender_id"`
	// 消息接收者Id
	ReceiverID int32 `json:"receiver_id"`
	// 消息类型, 1: 文字, 2: 图片, 3: 文件, 4: 语音, 5: 视频, 6: 语音通话, 7: 视频通话
	MessageType int16 `json:"message_type"`
	// 消息内容
	Content string `json:"content"`
	// 发送类型, 1: 私聊, 2: 群聊
	SendType int16 `json:"send_type"`
	// 消息发送时间
	SendingTime time.Time `json:"sending_time"`
	// 消息读取时间
	ReceiveTime time.Time `json:"receive_time"`
}

type User struct {
	// 用户Id
	ID int32 `json:"id"`
	// 用户名
	Username string `json:"username"`
	// 用户昵称
	Nickname string `json:"nickname"`
	// 密码
	Password string `json:"password"`
	// 邮箱
	Email string `json:"email"`
	// 性别, 1 男, 2 女, 3 未知
	Gender int16 `json:"gender"`
	// 头像图片路径或链接
	ProfilePictureUrl string `json:"profile_picture_url"`
	// 密码更新时间
	PasswordChangedAt time.Time `json:"password_changed_at"`
	// 最后在线时间
	LastLoginAt time.Time `json:"last_login_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}
