// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AddFriend(ctx context.Context, arg *AddFriendParams) (Friend, error)
	AddMessage(ctx context.Context, arg *AddMessageParams) (Message, error)
	AddUserLoginLog(ctx context.Context, arg *AddUserLoginLogParams) (UserLoginLog, error)
	CreateFriendClsuterApply(ctx context.Context, arg *CreateFriendClsuterApplyParams) (FriendClusterApply, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (User, error)
	DeleteFriend(ctx context.Context, arg *DeleteFriendParams) error
	DeleteUser(ctx context.Context, id int32) error
	ExistsFriendClusterApply(ctx context.Context, arg *ExistsFriendClusterApplyParams) (int64, error)
	GetFriend(ctx context.Context, arg *GetFriendParams) (Friend, error)
	GetLastUserLoginLog(ctx context.Context, userID int32) (UserLoginLog, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListFriendClusterApply(ctx context.Context, receiverID int32) ([]ListFriendClusterApplyRow, error)
	ListFriends(ctx context.Context, id int32) ([]ListFriendsRow, error)
	// DELETE FROM friend_cluster_apply
	// WHERE apply_id = $1 AND reply_id = $2;
	UpdateFriendClusterApply(ctx context.Context, arg *UpdateFriendClusterApplyParams) error
	UpdateFriendNote(ctx context.Context, arg *UpdateFriendNoteParams) (Friend, error)
	UpdateLastUserLoginLog(ctx context.Context, userID int32) error
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
