// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, nickname, password, gender
) VALUES(
    $1, $2, $3, $4, $5
)
RETURNING id, username, email, nickname, password, gender, avatar, register_time
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Gender   int16  `json:"gender"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Nickname,
		arg.Password,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Nickname,
		&i.Password,
		&i.Gender,
		&i.Avatar,
		&i.RegisterTime,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, nickname, password, gender, avatar, register_time FROM users
WHERE username = $1
OR email = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Nickname,
		&i.Password,
		&i.Gender,
		&i.Avatar,
		&i.RegisterTime,
	)
	return i, err
}

const loginUser = `-- name: LoginUser :one
SELECT id, username, email, nickname, password, gender, avatar, register_time FROM users
WHERE (username = $1 AND password = $2)
OR (email = $1 AND password = $2) LIMIT 1
`

type LoginUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) LoginUser(ctx context.Context, arg LoginUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, loginUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Nickname,
		&i.Password,
		&i.Gender,
		&i.Avatar,
		&i.RegisterTime,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = COALESCE($1, email),
    nickname = COALESCE($2, nickname),
    password = COALESCE($3, password),
    gender = COALESCE($4, gender),
    avatar = COALESCE($5, avatar)
WHERE
    username = $6
RETURNING id, username, email, nickname, password, gender, avatar, register_time
`

type UpdateUserParams struct {
	Email    sql.NullString `json:"email"`
	Nickname sql.NullString `json:"nickname"`
	Password sql.NullString `json:"password"`
	Gender   sql.NullInt16  `json:"gender"`
	Avatar   sql.NullString `json:"avatar"`
	Username string         `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Nickname,
		arg.Password,
		arg.Gender,
		arg.Avatar,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Nickname,
		&i.Password,
		&i.Gender,
		&i.Avatar,
		&i.RegisterTime,
	)
	return i, err
}
