// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Contact struct {
	// 主键Id
	ID int64 `json:"id"`
	// 谁的关系
	OwnerID int64 `json:"owner_id"`
	// 对应的谁
	TargetID int64 `json:"target_id"`
	// 对应类型, 1: 好友, 2: 群组
	Type int16 `json:"type"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	// 主键Id
	ID int64 `json:"id"`
	// 用户名
	Username string `json:"username"`
	// 用户邮箱
	Email string `json:"email"`
	// 用户昵称
	Nickname string `json:"nickname"`
	// 密码
	Password string `json:"password"`
	// 1: 男, 2: 女, 3: 未知
	Gender int16 `json:"gender"`
	// 用户头像
	Avatar string `json:"avatar"`
	// 注册时间
	RegisterTime time.Time `json:"register_time"`
}
