// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: chat_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	ChatMessage(ctx context.Context, opts ...grpc.CallOption) (ChatService_ChatMessageClient, error)
	SenderMessage(ctx context.Context, opts ...grpc.CallOption) (ChatService_SenderMessageClient, error)
	ReceiverMessage(ctx context.Context, opts ...grpc.CallOption) (ChatService_ReceiverMessageClient, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) ChatMessage(ctx context.Context, opts ...grpc.CallOption) (ChatService_ChatMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], "/qianxia.IMChat.ChatService/ChatMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceChatMessageClient{stream}
	return x, nil
}

type ChatService_ChatMessageClient interface {
	Send(*ChatMeg) error
	Recv() (*ChatMeg, error)
	grpc.ClientStream
}

type chatServiceChatMessageClient struct {
	grpc.ClientStream
}

func (x *chatServiceChatMessageClient) Send(m *ChatMeg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceChatMessageClient) Recv() (*ChatMeg, error) {
	m := new(ChatMeg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) SenderMessage(ctx context.Context, opts ...grpc.CallOption) (ChatService_SenderMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[1], "/qianxia.IMChat.ChatService/SenderMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceSenderMessageClient{stream}
	return x, nil
}

type ChatService_SenderMessageClient interface {
	Send(*SenderMessageRequest) error
	Recv() (*SenderMessageResponse, error)
	grpc.ClientStream
}

type chatServiceSenderMessageClient struct {
	grpc.ClientStream
}

func (x *chatServiceSenderMessageClient) Send(m *SenderMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceSenderMessageClient) Recv() (*SenderMessageResponse, error) {
	m := new(SenderMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) ReceiverMessage(ctx context.Context, opts ...grpc.CallOption) (ChatService_ReceiverMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[2], "/qianxia.IMChat.ChatService/ReceiverMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceReceiverMessageClient{stream}
	return x, nil
}

type ChatService_ReceiverMessageClient interface {
	Send(*SenderMessageResponse) error
	Recv() (*ReceiverMessageRequest, error)
	grpc.ClientStream
}

type chatServiceReceiverMessageClient struct {
	grpc.ClientStream
}

func (x *chatServiceReceiverMessageClient) Send(m *SenderMessageResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceReceiverMessageClient) Recv() (*ReceiverMessageRequest, error) {
	m := new(ReceiverMessageRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	ChatMessage(ChatService_ChatMessageServer) error
	SenderMessage(ChatService_SenderMessageServer) error
	ReceiverMessage(ChatService_ReceiverMessageServer) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) ChatMessage(ChatService_ChatMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatMessage not implemented")
}
func (UnimplementedChatServiceServer) SenderMessage(ChatService_SenderMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SenderMessage not implemented")
}
func (UnimplementedChatServiceServer) ReceiverMessage(ChatService_ReceiverMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiverMessage not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_ChatMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).ChatMessage(&chatServiceChatMessageServer{stream})
}

type ChatService_ChatMessageServer interface {
	Send(*ChatMeg) error
	Recv() (*ChatMeg, error)
	grpc.ServerStream
}

type chatServiceChatMessageServer struct {
	grpc.ServerStream
}

func (x *chatServiceChatMessageServer) Send(m *ChatMeg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceChatMessageServer) Recv() (*ChatMeg, error) {
	m := new(ChatMeg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatService_SenderMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).SenderMessage(&chatServiceSenderMessageServer{stream})
}

type ChatService_SenderMessageServer interface {
	Send(*SenderMessageResponse) error
	Recv() (*SenderMessageRequest, error)
	grpc.ServerStream
}

type chatServiceSenderMessageServer struct {
	grpc.ServerStream
}

func (x *chatServiceSenderMessageServer) Send(m *SenderMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceSenderMessageServer) Recv() (*SenderMessageRequest, error) {
	m := new(SenderMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatService_ReceiverMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).ReceiverMessage(&chatServiceReceiverMessageServer{stream})
}

type ChatService_ReceiverMessageServer interface {
	Send(*ReceiverMessageRequest) error
	Recv() (*SenderMessageResponse, error)
	grpc.ServerStream
}

type chatServiceReceiverMessageServer struct {
	grpc.ServerStream
}

func (x *chatServiceReceiverMessageServer) Send(m *ReceiverMessageRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceReceiverMessageServer) Recv() (*SenderMessageResponse, error) {
	m := new(SenderMessageResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qianxia.IMChat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatMessage",
			Handler:       _ChatService_ChatMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SenderMessage",
			Handler:       _ChatService_SenderMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceiverMessage",
			Handler:       _ChatService_ReceiverMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat_service.proto",
}
